### ISSUE TITLE
Inserir dados relacionais

### ISSUE THREAD

**Issue by KauaGrathwohl** [KauaGrathwohl/projeto-final-engenharia-dados-satc#3]
Ter um banco de dados relacional rodando, com os dados inseridos nas tabelas corretamente.

**Comment by thiagolarangeiras** [comment]
Banco de Dados Relacional (RDBMS) escolhido: SQL-Server (MSSQL)
Script de criação da estrutura: ` /data/raw/schema.sql`
Script com tudo junto para criação rapida: `./data/raw/dump.sql`
