### ISSUE TITLE
Script para camada Landing

### ISSUE THREAD

**Issue by KauaGrathwohl** [KauaGrathwohl/projeto-final-engenharia-dados-satc#4]
Script Python que irá gerar um CSV, com base nos dados relacionais.  Deve-se inserir os mesmos dados na plataforma Azure/Minio.

**Comment by thiagolarangeiras** [comment]
To fazendo

**Comment by thiagolarangeiras** [comment]
Tudo joia

**Comment by thiagolarangeiras** [comment]
seram feitos ajustes conforme mexer na pipeline
