### ISSUE TITLE
Tratamento de dados (Databricks)

### ISSUE THREAD

**Issue by KauaGrathwohl** [KauaGrathwohl/projeto-final-engenharia-dados-satc#5]
Tratamento de dados da camada Landing para as camadas Bronze, Silver e Gold.

**Comment by thiagolarangeiras** [comment]
# Partes a serem feitas:
* bronze -  
* prata
* ouro

**Comment by thiagolarangeiras** [comment]
Inicio do codigo colocado na branch thiago
